# Generated by Django 5.2.13 on 2026-04-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('documento_identidad', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('fecha_asistencia', models.DateField()),
                ('hora_ingreso', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('presente', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha_asistencia', 'nombre_completo'],
            },
        ),
    ]
