# Generated by Django 5.1 on 2026-04-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(help_text='Nombre completo de quien realiza la solicitud', max_length=150, verbose_name='Nombre del solicitante')),
                ('documento_identidad', models.CharField(help_text='Cédula, pasaporte u otro documento de identificación', max_length=50, verbose_name='Documento de identidad')),
                ('correo_electronico', models.EmailField(help_text='Correo de contacto válido', max_length=254, verbose_name='Correo electrónico')),
                ('telefono_contacto', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('tipo_solicitud', models.CharField(choices=[('academica', 'Académica'), ('administrativa', 'Administrativa'), ('tecnica', 'Técnica'), ('otra', 'Otra')], help_text='Selecciona la categoría de tu solicitud', max_length=20, verbose_name='Tipo de solicitud')),
                ('asunto', models.CharField(help_text='Resumen breve del motivo de la solicitud', max_length=200, verbose_name='Asunto')),
                ('descripcion_detallada', models.TextField(help_text='Explica en detalle tu solicitud', verbose_name='Descripción detallada')),
                ('fecha_solicitud', models.DateField(auto_now_add=True, help_text='Se registra automáticamente la fecha actual', verbose_name='Fecha de solicitud')),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Puedes adjuntar documentos de soporte (opcional)', null=True, upload_to='adjuntos/', verbose_name='Archivo adjunto')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['-fecha_solicitud'], name='solicitudes_fecha_s_bf80bd_idx'), models.Index(fields=['tipo_solicitud'], name='solicitudes_tipo_so_96d0d1_idx')],
            },
        ),
    ]
